cpp_compiler := $(ELF_GCC)
asm_compiler := 

int_dir := $(int_dir)/libc
bin_dir := $(bin_dir)/libc

includes := include internal

compile_flags := -g -ffreestanding -fno-stack-protector -fno-exceptions

out_file := libc.a

include $(build_dir)/makefile/cpp_static.mk